{
 "title": "Solana Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vote_account",
    "label": "Vote Account",
    "query": {
     "query": "label_values(solana_slot, vote_account)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Activated Stake (USD)",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(solana_stake{vote_account=\"$vote_account\", stake_type=\"activated\"} / 1e9) * ignoring(stake_type) group_left() (solana_usd_price{vote_account=\"$vote_account\"} / 1e5)",
     "legendFormat": "Activated Stake (USD)"
    }
   ]
  },
  {
   "title": "Activated Stake (SOL)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_stake{vote_account=\"$vote_account\", stake_type=\"activated\"} / 1e9",
     "legendFormat": "Activated Stake (SOL)"
    }
   ]
  },
  {
   "title": "Stake Delta (SOL)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(solana_stake{vote_account=\"$vote_account\", stake_type=\"activating\"} - ignoring(stake_type) group_left() solana_stake{vote_account=\"$vote_account\", stake_type=\"deactivating\"}) / 1e9",
     "legendFormat": "Stake Delta (SOL)"
    }
   ]
  },
  {
   "title": "Vote Credit Rank",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_vote_credit_rank{vote_account=\"$vote_account\"}",
     "legendFormat": "Vote Credit Rank"
    }
   ]
  },
  {
   "title": "Vote Efficiency ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "solana_vote_credits_efficiency{vote_account=\"$vote_account\"} / 100",
     "legendFormat": "Skip Rate"
    }
   ]
  },
  {
   "title": "SOL Price (USD)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_usd_price{vote_account=\"$vote_account\"} / 1e5",
     "legendFormat": "SOL Price (USD)"
    }
   ]
  },
  {
   "title": "Epoch Block Rewards (SOL)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_epoch_block_rewards{vote_account=\"$vote_account\"} / 1e9",
     "legendFormat": "Epoch Block Rewards (SOL)"
    }
   ]
  },
  {
   "title": "Time to Next Leader Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_ms_to_next_slot{vote_account=\"$vote_account\"}",
     "legendFormat": "Time to Next Leader Slot"
    }
   ]
  },
  {
   "title": "Skip Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_blocks{vote_account=\"$vote_account\", block_type=\"skipped\"} / ignoring(block_type) group_left() (solana_blocks{vote_account=\"$vote_account\", block_type=\"produced\"} + ignoring(block_type) group_left() solana_blocks{vote_account=\"$vote_account\", block_type=\"skipped\"})",
     "legendFormat": "Skip Rate"
    }
   ]
  },
  {
   "title": "Current Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "targets": [
    {
     "expr": "solana_slot{vote_account=\"$vote_account\"}",
     "legendFormat": "Skip Rate"
    }
   ]
  },
  {
   "title": "Balances (SOL)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "solana_identity_balance{vote_account=\"$vote_account\"} / 1e9",
     "legendFormat": "Identity Account"
    }
   ]
  },
  {
   "title": "Avg Block Rewards (Last 4 Slots)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "solana_last_block_rewards{vote_account=\"$vote_account\"} / 1e9",
     "legendFormat": "Avg Block Rewards"
    }
   ]
  },
  {
   "title": "Jito Tips",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "solana_jito_tips{vote_account=\"$vote_account\"} / 1e9",
     "legendFormat": "Total Jito Tips"
    }
   ]
  },
  {
   "title": "Total Leader Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_blocks{vote_account=\"$vote_account\", block_type=\"total\"}",
     "legendFormat": "Total Leader Slots"
    }
   ]
  },
  {
   "title": "Remaining Leader Slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_blocks{vote_account=\"$vote_account\", block_type=\"total\"} - ignoring(block_type) group_left() (solana_blocks{vote_account=\"$vote_account\", block_type=\"produced\"} + ignoring(block_type) group_left() solana_blocks{vote_account=\"$vote_account\", block_type=\"skipped\"})",
     "legendFormat": "Remaining Leader Slots"
    }
   ]
  },
  {
   "title": "Epoch Progress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_epoch_progress{vote_account=\"$vote_account\"} / 1e2",
     "legendFormat": "Epoch Progress"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_epoch{vote_account=\"$vote_account\"}",
     "legendFormat": "Current Epoch"
    }
   ]
  },
  {
   "title": "Block Production",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_blocks{vote_account=\"$vote_account\", block_type=\"produced\"}",
     "legendFormat": "{{block_type}}"
    },
    {
     "expr": "solana_blocks{vote_account=\"$vote_account\", block_type=\"skipped\"}",
     "legendFormat": "{{block_type}}"
    }
   ]
  },
  {
   "title": "Skipped Slots",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Slots" } },
   "targets": [
    {
     "expr": "solana_blocks{vote_account=\"$vote_account\", block_type=\"skipped\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Missed Vote Credits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Credits" } },
   "targets": [
    {
     "expr": "solana_vote_credits_max{vote_account=\"$vote_account\"} - solana_vote_credits_earned{vote_account=\"$vote_account\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activated Stake Accounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_stake{vote_account=\"$vote_account\", stake_type=\"activated_accounts\"}",
     "legendFormat": "Activated Stake Accounts"
    }
   ]
  },
  {
   "title": "Activating Stake Accounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_stake{vote_account=\"$vote_account\", stake_type=\"activating_accounts\"}",
     "legendFormat": "Activating Stake Accounts"
    }
   ]
  },
  {
   "title": "Deactivating Stake Accounts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solana_stake{vote_account=\"$vote_account\", stake_type=\"deactivating_accounts\"}",
     "legendFormat": "Deactivating Stake Accounts"
    }
   ]
  }
 ]
}